version: '3.7'
services:
    app:
        container_name: front
        build:
            context: ./front
            dockerfile: Dockerfile
        volumes:
            - './front:/app'
            - '/app/node_modules'
        ports:
            - '3001:3000'
        environment:
            - NODE_ENV=development